---
name: "Gen Tests"

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  gen-tests:
    name: Generate Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Unit Test Generator
      uses: revantk/gen-tests-action@main
      with:
        robustai-api-key: ${{ secrets.ROBUSTAI_API_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
